[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
goroorog = "7FyBUa4ZCA2krXYmSkJW6jdfZGVUpF6wTbYNUE5jRFyq"

[programs.devnet]
goroorog = "7FyBUa4ZCA2krXYmSkJW6jdfZGVUpF6wTbYNUE5jRFyq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
